version: "3"
services:
  Own_cloud:
    image: owncloud:latest
    restart: always
    ports:
      - 8080:80

  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=example_123

  check-db:
	image:mysql:latest
	ports:
	 - "3308:3306"
	enviroment:
	 - MYSQL_ROOT_PASSWORD=example_123
	 - MYSQL_ROOT_USER=root
	 - MYSQL_USER=User
