version: "3"
services:
  Own_cloud:
    image: owncloud:10.0.10-apache
    restart: always
    ports:
      - 8080:80

  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=17/04162Dk

  www:
    image: phpmyadmin
    ports:
      - "82:80"
    environment:
      - PMA_ARBITRARY=1